### PR TITLE
Revive --exclude option in a new incarnation

### PR DESCRIPTION
**Pull request by Munter**
So this old thing popped up again :)

We caught a use case where assetgraph-builder would be run along side a different build system, which handles a sub-section of a site. The assetgraph-builder part of the site would link to the part outside, thus populating it against the authors intention.

The `--exclude` option lets you define a series of blacklist patterns matching on asset urls. This way specific assets can be blocked from being populated.

### CODE REVIEW

**Comment by papandreou** [comment]
Hmm, looks fine, but it's probably a bit deceptive that it's masquerading as a file system wildcard-based feature, but will actually be matched against the url. That'll work bad for non-url safe characters (eg. `*/fooæ.bar` won't match `file:///path/to/foo%C3%A6.bar`, even though that is the file url-ification of that file name.

I'm aware that this problem existed with the old implementation as well. Also, I'm not sure how to fix it so behaves predictably for both http urls and files on disc. The primary use case for you is file system paths, right?

**Comment by Munter** [comment]
I think the only use case is file system paths, seeing as those are the only ones covered by assetgraph-builders default queries. If any non-file urls start loading it's probably from very explicit transforms, like internalising webfonts etc. Best not exclude those.

I could change it so it always assumes the pattern always starts at the assetgraph root, like I've done for patterns starting with `/`

**Comment by papandreou** [comment]
Okay, thanks for clarifying. Then I'd feel better about only allowing file system wildcards for now.

> I could change it so it always assumes the pattern always starts at the assetgraph root, like I've done for patterns starting with /

I think it would be less surprising if they were anchored at the cwd so it would match how the "initial" assets are specified as non-option parameters to `buildProduction`?

**Comment by Munter** [comment]
Updated to match patterns relative to `process.cwd()`

**Comment by papandreou** [comment]
Could you add a test case for excluding a file name containing non-url safe characters, such as `æ.txt`? IMO that should be spelled `buildProduction --exclude æ.txt`, even though the url will have contain percent encoded octets (`file:///path/to/root/%C3%A6.txt`).

**Pull request merged**
