### PR TITLE
Source map support, adapt to CSSOM being replaced by postcss

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
This works in the couple of One.com web apps I've tested it with, and with charcod.es.

@Munter Could be fun to try it out on yeoman.io, is it easy to get that to build locally?

**Comment by Munter** [comment]
I can do that. What am I looking for?

**Comment by papandreou** [comment]
Does `buildProduction --sourcemaps ...` produce a working build? If you mount the dir with the source files with Chrome's devtools, are the CSS and JS bundles correctly mapped to the source files? Can you set a breakpoint in the original JS files, and is it triggered when the corresponding code in the bundle gets executed?

**Comment by Munter** [comment]
All of those scenarios seem to work. These are the built files: http://reduceyeoman.surge.sh/

**Comment by papandreou** [comment]
Sweet as a nut :)

**Comment by papandreou** [comment]
Hmm, the inline script at the bottom has a bogus `//# sourceMappingURL=` at the end.

**Comment by papandreou** [comment]
> Hmm, the inline script at the bottom has a bogus //# sourceMappingURL= at the end.

Fixed.

**Comment by papandreou** [comment]
@Munter Could you try building an app off a fusile-mounted dir to see if it gets the source locations right? I suspect you depend on `sourcesContent`, which is currently only propagated for CSS and only when `buildProduction --sourcescontent` is passed.

If fusile puts correct file:// urls into the `sources` array, it should work anyway, though.

**Comment by papandreou** [comment]
@bramstein Could you try this out on Typekit Practice or some other non-trivial static page? Just add `--sourcemaps` to the `buildProduction` command line.

**Comment by papandreou** [comment]
@Munter Fixed the Fusile source map problem.

**Comment by papandreou** [comment]
The source map inline in main.js specifies the same source file twice, first with an absolute path, then with a relative one:

```
$ echo eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL211bnRlci9hc3NldGdyYXBoL2J1aWxkZXIvZGVtb2FwcC9tYWluLnNjc3MiLCJkZW1vYXBwL21haW4uc2NzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTtFQUNFLDBCQUEwQixFQUR6Qjs7QUNJSDtFQUNFLDBCQUxtQixFQUlmOztBQUlOO0VBQ0UsaUNBQWlCO1VBQWpCLHlCQUFpQixFQURmIiwiZmlsZSI6InRvLmNzcyJ9 | base64 -d | jq .
{
  "version": 3,
  "sources": [
    "/home/munter/assetgraph/builder/demoapp/main.scss",
    "demoapp/main.scss"
  ],
  "names": [],
  "mappings": "AAAA;EACE,0BAA0B,EADzB;;ACIH;EACE,0BALmB,EAIf;;AAIN;EACE,iCAAiB;UAAjB,yBAAiB,EADf",
  "file": "to.css"
}
```

That causes those two entries to also be in the output from `buildProduction`.

Interally I've chosen to normalize those paths to absolute urls, typically `file:///...`. That makes it a lot easier to ensure that they come out correctly.

**Comment by Munter** [comment]
Interesting. I wonder if that is my bug or accords

**Comment by papandreou** [comment]
Is there an `@import` in the original scss file? I noticed some pretty flaky node-sass behavior when I added source map support to the `compileSassToCss` transform. Somehow the generated source that came from an `@import`ed file pointed at the `@import` rather than the original location of the rules that were generated. I forgot to report that, but it sounds like it could be the same bug.

**Comment by Munter** [comment]
Yes. The original has a `fonts.scss` which is `@import`ed. Compiled with node-sass 3.3.3 by fusile through accord

**Pull request merged**
