### PR TITLE
tests: migrate CSSO justDoIt method to minify method

### PR DESCRIPTION
**Pull request by DanielRuf**
This fixes the failing CI builds.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Now we see the actual errors.

**Comment by papandreou** [comment]
Thanks for tackling this! I think the 3rd error comes from a regression in postcss that will be fixed once we release a new version of assetgraph and update to it.

**Comment by DanielRuf** [comment]
> Thanks for tackling this! I think the 3rd error comes from a regression in postcss that will be fixed once we release a new version of assetgraph and update to it.

Do you know which PR or change will fix this?

**Comment by papandreou** [comment]
This one: https://github.com/assetgraph/assetgraph/commit/2da59864e531147cd4d8162f1f71e0ea0ba3ca37

I've released assetgraph 5.4.2 and updated to it on master now, let's cross our fingers :crossed_fingers:

**Comment by DanielRuf** [comment]
Seems to be better now: https://travis-ci.org/assetgraph/assetgraph-builder/jobs/486160944

**Comment by DanielRuf** [comment]
https://travis-ci.org/assetgraph/assetgraph-builder/jobs/486160944

**Comment by papandreou** [comment]
That's nice! There's a bit of whack-a-mole with the new tests failing, but I'll look into that :)

**Comment by papandreou** [comment]
There, fixed all [but one](https://travis-ci.org/assetgraph/assetgraph-builder/jobs/486174210#L1576-L1596) now. Seems like that's due to canvas-prebuilt not being available for node.js 11.

**Comment by DanielRuf** [comment]
Is it the latest release of canvas-prebuilt? If so we can maybe allow it to fail until it is fixed.

**Comment by papandreou** [comment]
Yeah, [assetgraph-sprite@3.0.1 uses canvas-prebuilt@2.0.0-alpha.14](https://github.com/assetgraph/assetgraph-sprite/blob/579a8ed7f89d35283e4541110149422ac606aab5/package.json#L44), which is the latest according to https://www.npmjs.com/package/canvas-prebuilt

There are some newer tags in the canvas-repo, such as [v2.3.1](https://github.com/node-gfx/node-canvas-prebuilt/tree/v2.3.1), but they aren't published to npm, and they fail when I try to install them via `npm i node-gfx/node-canvas-prebuilt#v2.3.1`.

Hopefully it will be sorted out soon. In the mean time we should probably allow the node 11 build to fail.

**Comment by papandreou** [comment]
Finally got the build to pass on master now by switching from `canvas-prebuilt` to `canvas`. Apparently the former is now deprecated :sweat_smile:

Try rebasing your branch now, that should reduce the noise :)

**Comment by papandreou** [comment]
@DanielRuf, you've deleted your fork, have you backed out of this PR? 😢

**Comment by DanielRuf** [comment]
I just cleaned up my profile. The code is still there and I can provide a fresh PR if needed.

**Comment by DanielRuf** [comment]
Looks better now. Shall I inspect the failing tests?

https://travis-ci.org/assetgraph/assetgraph-builder/jobs/509669470

**Comment by papandreou** [comment]
Thanks! I'm debugging it locally, trying to find out what's going on.

**Comment by papandreou** [comment]
The `bundleRequireJs` transform ends up trying to parse `[object Object]` as CSS :laughing:

**Comment by papandreou** [comment]
This seems to work: https://github.com/assetgraph/assetgraph-builder/commit/f53148dc085af47667f841fc12f43533f29c104c

**Comment by papandreou** [comment]
Thanks for the contribution! :tada:

**Comment by DanielRuf** [comment]
Ah, the `.css` part. So I forgot to add this.

**Comment by DanielRuf** [comment]
Not sure if I oversaw this in the (migration) docs.

Sorry for creating extra work.
But maybe we can catch this in the unit tests (check if JSON or CSS, not yet sure how exactly).

**Comment by papandreou** [comment]
I don't know if it's worth it, as these are checked in copies of specific versions of some require.js plugins only used in the test suite.

**Pull request merged**
