### PR TITLE
Add dpr setting to processImages transform

### PR DESCRIPTION
**Pull request by Munter**
Relates to https://github.com/assetgraph/assetgraph-sprite/pull/13#issuecomment-68345087

Add support for setting the device pixel ratio of the image asset that is the result of a `processImage` run.
The idea here is to be able to set the device pixel ratio as part of the image pipeline without having to set the device pixel ration in the filename itself, given that the file name cannot contain the `@2x` syntax if the image pipeline is what creates the image.

I've changed the behavior so `dpr=/\d+(?:[,\.]\d+)?/` gets removed from the url during the transform, and the corresponding device pixel ratio is applied to the resulting new asset or the existing asset if no new one is created.

This means that more of the code in the transform is now run than before, since the whole used/unused query string logic was only in use if filters were applied. Now these parts are in play for every asset.

@papandreou what do you think of this?

Ping @silvenon

### CODE REVIEW

**Comment by silvenon** [comment]
> device pixel ration

I also accidentally type "ration" instead of "ratio", **always**. I have no idea why that is happening :smiley:

> given that the file name cannot contain the `@2x` syntax if the image pipeline is what creates the image.

Will something bad happen if the filename is using the `@` syntax? It will just not be parsed as a dpr, right?

> I've changed the behavior so `dpr=/\d+(?:[,\.]\d+)?/` gets removed from the url during the transform, and the corresponding device pixel ratio is applied to the resulting new asset or the existing asset if no new one is created.

So it would be used like this?

```css
.foo {
  background-image: url(images/bar.png?resize=32);
}

@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
  .foo {
    background-image: url(images/bar.png?resize=64&dpr=2);
    background-size: 32px;
  }
}
```

Also, the order of the `dpr` parameter doesn't matter, right?

**Comment by Munter** [comment]
> Will something bad happen if the filename is using the @ syntax? It will just not be parsed as a dpr, right?

It will, but in a different part of the life cycle. If a file has such a name the dpr will be set upon creation of the `Image` asset in the graph. if it has `?dpr=2` that ratio will be set when the `processImages` transform is run.

Your example is exactly how it would work.

> Also, the order of the dpr parameter doesn't matter, right?

Correct. I tried thinking about how to take dpr into account as a modifier of following operations, but gave up on it, since most of this logic resides outside the scope of assetgraph and thus has no knowledge of dpr.

**Comment by silvenon** [comment]
Ok, got it.

**Comment by Munter** [comment]
Allright, I haven't come up with any reason not to add this patch. Merging

**Comment by Munter** [comment]
Released in:
- assetgraph-builder 2.10.0
- grunt-reduce 1.3.0
- generator-greenfield 1.5.0

**Comment by silvenon** [comment]
:+1: :+1: :+1:

**Pull request merged**
