### PR TITLE
Reduce external dependencies

### LINKED ISSUE #625: `node-zopfli` package seems no longer maintained
[Seemingly abandoned](https://github.com/pierreinglebert/node-zopfli/issues/87) multiple months back. Binaries no longer available from AWS.

### Options
`bruce-one/node-zopfli` fork was reported to work.

This worked for me, but I _have_ build tools installed
```bash
$ npm install --build-from-source node-zopfli
```

### PR DESCRIPTION
**Pull request by Munter**
Refs #627
Fixes #625

- Remove `jpegtran`, `pngquant`, `optipng`, `pngcrush` and `gifsicle` OS-level dependency and install instructions. Already part of npm install
- Update to newer histogram implementation without an OS-level dependency on `cairo`, `libjpeg`, `libgif` and `libpango`
- Remove all unnessessary OS-level dependencies mentioned in README, travis config and Dockerfile

We should also consider moving `node-zopfli` optionalDependency into devDependency and just not spam the users with failed installation messages for optional depednencies, which npm really puts to much emphasis on. The fallback at runtime is that assetgraph emits an event about a possible improvement if you install `node-zopfli`, but there will be no failure.

### CODE REVIEW

**Comment by Munter** [comment]
The point of removing these OS-level dependencies are that the node-installed versions of these already come with their binaries. So they're essentially just noise in our installation instructions. The npm dependencies are what makes it continue to work

**Comment by Munter** [comment]
The true test is of course removing those in the travis config. Coming up...

**Comment by papandreou** [comment]
Ah, okay, makes sense 👍

**Comment by Munter** [comment]
This last build error was intentional. I've removed the dependencies needed to build assetgraph-sprite in the current version. I expect the build to go green when we depend on the next version with cairo external dependency removed

**Comment by Munter** [comment]
Looks like there is a problem with express-processimage somewhere between 8.0.0 and 8.0.2 which causes Travis and my local machine to both fail with: https://travis-ci.org/assetgraph/assetgraph-builder/jobs/462165078#L748-L759

**Comment by papandreou** [comment]
I think I've seen that failure on CI before, but I can't reproduce it locally :(

**Comment by papandreou** [comment]
I fixed the express-processimage problem on master and upgraded to 8.1.0.

**Comment by papandreou** [comment]
@Munter, can we merge this now, or is there still work left to do?

**Comment by Munter** [comment]
I think the things I really wanted to fix are done. There's probably possible optimizations left, but at least the reduction to only two optional OS-level installations is nice. So I think we should merge

**Comment by plroebuck** [comment]
Sweet! What release?

**Comment by papandreou** [comment]
@plroebuch, 6.10.0, released 4 seconds ago :sunglasses:

**Pull request merged**
